### ISSUE TITLE
is it possible to implement with normal web

### ISSUE THREAD

**Issue by infacq** [keyvanfatehi/asteroid-facebook-connect#2]

**Comment by kfatehi** [comment]
I think the default behavior was web authentication. This repo is for monkeypatching this default behavior to work using the cordova plugin. You should read the comments in here https://github.com/kfatehi/asteroid-facebook-connect/blob/master/client.js

**Comment by kfatehi** [comment]
The readme also addresses your inquiry:
> You should load this one instead of the one prescribed by asteroid for facebook. The one asteroid docs tells you to use is not for facebook-connect (native facebook login) but for oauth (web browser popup), which is not desired in mobile apps.

**Comment by infacq** [comment]
thanks @kfatehi. I agree with you. How about Google? Should we avoid also?

**Comment by kfatehi** [comment]
I don't know. I only had facebook login in the app for which I built this
module.
